name: Deploy to ECS

on:
  push:
    branches:
      - main

jobs:
  depoly:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Build Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devops-app:latest ./app

      - name: Push Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/devops-app:latest

      - name: COnfigure AWS
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to ECS
        run: |
          aws ecs update-service \
            --cluster devops-cluster \
            --service devops-service \
            --force-new-deployment